import { Link } from "react-router-dom";
import { Scale, AlertTriangle } from "lucide-react";

const AppFooter = () => {
  return (
    <footer data-testid="app-footer">
      {/* Full Legal Disclaimer — Bold & Visible on Every Page */}
      <div className="bg-red-700 py-5 px-6" data-testid="footer-legal-disclaimer">
        <div className="max-w-5xl mx-auto">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-white shrink-0 mt-0.5" />
            <div>
              <p className="text-white font-extrabold text-base uppercase tracking-wide mb-2">
                NOT LEGAL ADVICE
              </p>
              <p className="text-white font-bold text-sm leading-relaxed">
                This application is an educational research tool only and does NOT constitute legal advice. It must NOT be relied upon as such. The creator of this application is not a lawyer. All analysis, findings, reports, and recommendations generated by this tool must be independently verified by a qualified Australian legal professional before any action is taken. This tool covers Australian law only. No solicitor-client relationship is created by using this service.
              </p>
              <p className="text-white/80 text-xs mt-3">
                <Link to="/terms" className="text-white underline hover:text-white/90" data-testid="footer-disclaimer-terms-link">
                  Read full Terms & Privacy Policy
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="py-6 px-6 bg-slate-800">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-3 gap-3 sm:gap-4 items-start">
            <div className="flex flex-col items-start">
              <div className="flex items-center gap-1.5">
                <Scale className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-white" />
                <span className="text-white text-[10px] sm:text-xs font-bold leading-tight">Appeal Case Manager</span>
              </div>
              <span className="text-white/90 text-[10px] sm:text-xs mt-1 font-semibold leading-tight">Created and Designed by Deb King</span>
            </div>

            <div>
              <p className="text-[10px] sm:text-xs uppercase tracking-wide text-white/50 font-bold mb-1.5 sm:mb-2">&bull; Guides &bull;</p>
              <div className="grid gap-y-0.5 text-[10px] sm:text-xs">
                <Link to="/professional-summary" className="text-white font-bold hover:text-blue-300" data-testid="footer-professional-summary">For Legal Professionals</Link>
                <Link to="/appeal-statistics" className="text-white font-bold hover:text-blue-300" data-testid="footer-appeal-statistics">Appeal Statistics</Link>
                <Link to="/how-it-works" className="text-white font-bold hover:text-blue-300" data-testid="footer-how-it-works">How It Works</Link>
                <Link to="/how-to-use" className="text-white font-bold hover:text-blue-300" data-testid="footer-how-to-use">How To Use</Link>
                <Link to="/legal-framework" className="text-white font-bold hover:text-blue-300" data-testid="footer-legal-framework">Legal Framework</Link>
                <Link to="/glossary" className="text-white font-bold hover:text-blue-300" data-testid="footer-glossary">Legal Glossary</Link>
                <Link to="/legal-resources" className="text-white font-bold hover:text-blue-300" data-testid="footer-legal-resources">Resources & Contacts</Link>
              </div>
            </div>

            <div>
              <p className="text-[10px] sm:text-xs uppercase tracking-wide text-white/50 font-bold mb-1.5 sm:mb-2">&bull; Tools &bull;</p>
              <div className="grid gap-y-0.5 text-[10px] sm:text-xs">
                <Link to="/lawyers" className="text-white font-bold hover:text-blue-300" data-testid="footer-lawyers">Lawyer Directory</Link>
                <Link to="/forms" className="text-white font-bold hover:text-blue-300" data-testid="footer-forms">Forms & Templates</Link>
                <Link to="/caselaw-search" className="text-white font-bold hover:text-blue-300" data-testid="footer-caselaw-search">Caselaw Search</Link>
                <Link to="/about" className="text-white font-bold hover:text-blue-300" data-testid="footer-about">About</Link>
                <Link to="/faq" className="text-white font-bold hover:text-blue-300" data-testid="footer-faq">FAQ</Link>
                <Link to="/success-stories" className="text-white font-bold hover:text-blue-300" data-testid="footer-success-stories">Success Stories</Link>
                <Link to="/terms" className="text-white font-bold hover:text-blue-300" data-testid="footer-terms">Terms & Privacy</Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Copyright */}
      <div className="bg-slate-900 py-3 px-6 text-center" data-testid="footer-copyright">
        <p className="text-white/60 text-xs">&copy; 2025 Appeal Case Manager. Created and Designed by Deb King. All rights reserved.</p>
      </div>
    </footer>
  );
};

export default AppFooter;
