import { Link, useLocation } from "react-router-dom";
import { Scale, AlertTriangle } from "lucide-react";

const darkPages = ["/appeal-statistics"];

const AppFooter = () => {
  const location = useLocation();
  const isDark = darkPages.some(p => location.pathname.startsWith(p));

  const wrapperCls = isDark
    ? "py-8 px-6 border-t border-blue-500 bg-blue-700"
    : "py-8 px-6 border-t border-slate-200 bg-white";
  const iconCls = isDark ? "w-5 h-5 text-white" : "w-5 h-5 text-slate-700";
  const titleCls = isDark ? "text-white text-sm font-semibold" : "text-slate-900 text-sm font-semibold";
  const subCls = isDark ? "text-blue-200 text-xs" : "text-slate-600 text-xs";
  const headCls = isDark ? "text-xs uppercase tracking-wide text-blue-200 font-semibold mb-2" : "text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2";
  const linkCls = isDark ? "text-blue-100 hover:text-white visited:text-blue-100" : "text-slate-700 hover:text-blue-700 visited:text-slate-700";

  return (
    <footer data-testid="app-footer">
      <div className={wrapperCls}>
        <div className="max-w-5xl mx-auto grid md:grid-cols-3 gap-6 items-start">
          <div className="flex flex-col items-center md:items-start">
            <div className="flex items-center gap-2">
              <Scale className={iconCls} />
              <span className={titleCls}>Appeal Case Manager</span>
            </div>
            <span className={`${subCls} mt-1`}>Founded by Debra King</span>
            <span className={`${subCls} mt-0.5`}>Criminal Appeal Research Tool — Australian Law Only</span>
          </div>

          <div>
            <p className={headCls}>Explore</p>
            <div className="grid gap-y-1 text-xs">
              <Link to="/how-it-works" className={linkCls} data-testid="footer-how-it-works">How It Works</Link>
              <Link to="/how-to-use" className={linkCls} data-testid="footer-how-to-use">How To Use</Link>
              <Link to="/professional-summary" className={linkCls} data-testid="footer-professional-summary">For Legal Professionals</Link>
              <Link to="/legal-resources" className={linkCls} data-testid="footer-legal-resources">Resources & Contacts</Link>
              <Link to="/forms" className={linkCls} data-testid="footer-forms">Forms & Templates</Link>
              <Link to="/lawyers" className={linkCls} data-testid="footer-lawyers">Lawyer Directory</Link>
              <Link to="/contact" className={linkCls} data-testid="footer-contact">Contact</Link>
              <Link to="/success-stories" className={linkCls} data-testid="footer-success-stories">Success Stories</Link>
            </div>
          </div>

          <div>
            <p className={headCls}>Legal</p>
            <div className="grid gap-y-1 text-xs">
              <Link to="/appeal-statistics" className={linkCls} data-testid="footer-appeal-statistics">Appeal Statistics</Link>
              <Link to="/legal-framework" className={linkCls} data-testid="footer-legal-framework">Legal Framework</Link>
              <Link to="/glossary" className={linkCls} data-testid="footer-glossary">Legal Glossary</Link>
              <Link to="/faq" className={linkCls} data-testid="footer-faq">FAQ</Link>
              <Link to="/contact" className={linkCls} data-testid="footer-contact-legal">Contact</Link>
              <Link to="/about" className={linkCls} data-testid="footer-about">About</Link>
              <Link to="/terms" className={linkCls} data-testid="footer-terms">Terms & Privacy</Link>
            </div>
          </div>
        </div>
      </div>

      {/* Full Legal Disclaimer — Bold & Visible on Every Page */}
      <div className="bg-red-700 py-5 px-6" data-testid="footer-legal-disclaimer">
        <div className="max-w-5xl mx-auto">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-white shrink-0 mt-0.5" />
            <div>
              <p className="text-white font-extrabold text-base uppercase tracking-wide mb-2">
                NOT LEGAL ADVICE
              </p>
              <p className="text-white text-sm leading-relaxed">
                This application is an educational research tool only and does NOT constitute legal advice. It must NOT be relied upon as such. The creator of this application is not a lawyer. All analysis, findings, reports, and recommendations generated by this tool must be independently verified by a qualified Australian legal professional before any action is taken. This tool covers Australian law only. No solicitor-client relationship is created by using this service.
              </p>
              <p className="text-white/80 text-xs mt-3">
                <Link to="/terms" className="text-white underline hover:text-white/90" data-testid="footer-disclaimer-terms-link">
                  Read full Terms & Privacy Policy
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default AppFooter;
