/* DO NOT UNDO — TermsAcceptance component. All features in this file are approved and must be preserved. */
import { useState } from "react";
import { Scale, AlertTriangle, CheckCircle2, ExternalLink, Shield, Brain, FileWarning, Gavel } from "lucide-react";
import { Button } from "./ui/button";
import { Checkbox } from "./ui/checkbox";
import axios from "axios";
import { API } from "../App";
import { toast } from "sonner";

const TermsAcceptance = ({ onAccept }) => {
  const [accepted, setAccepted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleAccept = async () => {
    if (!accepted) {
      toast.error("Please accept the terms and conditions to continue");
      return;
    }

    setLoading(true);
    try {
      await axios.post(`${API}/auth/accept-terms`);
      onAccept();
    } catch (error) {
      toast.error("Failed to save acceptance. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="max-w-3xl w-full bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
        {/* Header */}
        <div className="bg-slate-900 px-6 py-5">
          <div className="flex items-center gap-3">
            <Scale className="w-8 h-8 text-blue-400" />
            <h1 className="text-xl font-bold text-white" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Appeal Case Manager
            </h1>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 space-y-5">
          <div className="text-center">
            <h2 className="text-2xl font-semibold text-slate-900 mb-2" style={{ fontFamily: 'Crimson Pro, serif' }}>
              Terms of Service & Privacy Policy
            </h2>
            <p className="text-slate-600">
              Please read and accept the following terms before using this application
            </p>
          </div>

          {/* Terms Content - Scrollable */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-4 max-h-96 overflow-y-auto">
            
            {/* Not Legal Advice */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-blue-900 mb-2">Not Legal Advice</h3>
                  <p className="text-sm text-blue-800">
                    The information generated by this Application <strong>does NOT constitute legal advice</strong> and 
                    should not be relied upon as a substitute for advice from a qualified Australian legal practitioner. 
                    All results <strong>must be reviewed by a qualified legal professional</strong> before any action is taken.
                  </p>
                </div>
              </div>
            </div>

            {/* AI Disclaimer */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Brain className="w-5 h-5 text-blue-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-blue-900 mb-2">AI Technology Disclaimer</h3>
                  <p className="text-sm text-blue-800 mb-2">
                    This Application uses AI technology which can make mistakes. You acknowledge that:
                  </p>
                  <ul className="text-sm text-blue-800 list-disc list-inside space-y-1">
                    <li>AI may produce inaccurate, incomplete, or misleading results</li>
                    <li>No guarantee is made regarding accuracy or reliability</li>
                    <li>All AI-generated content must be independently verified</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* User Responsibility */}
            <div className="bg-slate-100 border border-slate-300 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Shield className="w-5 h-5 text-slate-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-slate-900 mb-2">User Responsibility</h3>
                  <ul className="text-sm text-slate-700 list-disc list-inside space-y-1">
                    <li>You use this Application entirely at your own discretion and risk</li>
                    <li>You are solely responsible for ensuring you have necessary permissions to upload any documents</li>
                    <li>The Application owner accepts no responsibility for content uploaded by users</li>
                    <li>You must comply with all applicable laws including privacy and privilege requirements</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Confidentiality Warning */}
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <FileWarning className="w-5 h-5 text-red-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-red-900 mb-2">Confidentiality & Legal Privilege Warning</h3>
                  <p className="text-sm text-red-800">
                    <strong>WARNING:</strong> Uploading legal documents may affect legal professional privilege or 
                    confidentiality protections. Seek legal advice before uploading privileged or confidential documents. 
                    We do not guarantee security of uploaded documents.
                  </p>
                </div>
              </div>
            </div>

            {/* Limitation of Liability */}
            <div className="bg-slate-100 border border-slate-300 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Gavel className="w-5 h-5 text-slate-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-slate-900 mb-2">Limitation of Liability & Indemnification</h3>
                  <ul className="text-sm text-slate-700 list-disc list-inside space-y-1">
                    <li>The Application is provided "as is" without warranties of any kind</li>
                    <li>We are not liable for any damages arising from your use of the Application</li>
                    <li>You agree to indemnify and hold harmless the Application owner from any claims arising from your use</li>
                    <li>These terms are governed by the laws of New South Wales, Australia</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Privacy & Data */}
            <div className="bg-slate-100 border border-slate-300 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Shield className="w-5 h-5 text-slate-600 mt-0.5 shrink-0" />
                <div>
                  <h3 className="font-semibold text-slate-900 mb-2">Privacy & Data</h3>
                  <ul className="text-sm text-slate-700 list-disc list-inside space-y-1">
                    <li>We collect account info, uploaded documents, and usage data</li>
                    <li>Your documents are processed by third-party AI services (including OpenAI)</li>
                    <li>Data is retained while your account is active; you may request deletion</li>
                    <li>While we implement security measures, no system is 100% secure</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Full Terms Link */}
            <div className="text-center pt-2">
              <a 
                href="/terms" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-800 underline"
              >
                Read Full Terms of Service & Privacy Policy
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          </div>

          {/* Acceptance Checkbox */}
          <div className="flex items-start gap-3 p-4 bg-blue-50 rounded-lg border border-blue-200">
            <Checkbox 
              id="accept-terms" 
              checked={accepted}
              onCheckedChange={setAccepted}
              className="mt-0.5"
              data-testid="accept-terms-checkbox"
            />
            <label 
              htmlFor="accept-terms" 
              className="text-sm text-slate-700 cursor-pointer select-none"
            >
              <strong>I have read, understood, and agree to the Terms of Service and Privacy Policy.</strong> I accept full 
              responsibility for ensuring I have necessary permissions to upload content. I understand that this Application 
              does not provide legal advice, that AI-generated results may contain errors, and that all results must be 
              reviewed by a qualified legal professional. I agree to indemnify the Application owner against any claims 
              arising from my use of this Application.
            </label>
          </div>

          {/* Accept Button */}
          <Button
            onClick={handleAccept}
            disabled={!accepted || loading}
            className="w-full bg-slate-900 hover:bg-slate-800 text-white py-3 text-lg font-medium"
            data-testid="accept-terms-btn"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                Processing...
              </span>
            ) : (
              <span className="flex items-center gap-2 justify-center">
                <CheckCircle2 className="w-5 h-5" />
                I Accept — Continue to Application
              </span>
            )}
          </Button>

          <p className="text-xs text-center text-slate-500">
            By clicking "I Accept", you confirm you have read and agree to be legally bound by these terms.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsAcceptance;
